### ISSUE TITLE
Reduce Duplication in Test Package?

### ISSUE THREAD

**Issue by sbondorf** [NetCal/DNCext_MPARTC#6]
We duplicate the entire contents of the tests package to only change one line in DncTestArguments.java. Is there a way to use the unchanged files provided by the DiscoDNC core? 

I guess the *_Test.java files are required as they take the adapted DncTestArguments.class as test argument. But can we take the *_Network classes from the DiscoDNC v2.5.0 core jar?

Last, I think the duplicated PDF files that document the tests can be removed.

**Comment by matyesz** [comment]
This is a good question, I have to do some investigation. By default the content of the main/test is not visible for other projects according to my knowledge. I will check.

**Comment by sbondorf** [comment]
I found this on StackOverflow:
https://stackoverflow.com/questions/1725476/maven-test-dependency-in-multi-module-project/1733745#1733745

If that works, I also propose to move the test results currently in initializeBounds() into separate classes only present in the DiscoDNC core.

**Comment by matyesz** [comment]
Thanks for the article, I also found the same solution. I will remove the duplications.

**Comment by matyesz** [comment]
I did some coding and came out that if we remove unit_tests from the project they do not run at all at the moment as eclipse does not find them. Perhaps it is a much better idea to have a separate project for the tests that is used during testing scope (I also find it a bit nicer than hacking the jar creation and create a test jar too). Will spend some more time on this.
